with Ada.Text_IO, Ada.Integer_Text_IO;
use Ada.Text_IO, Ada.Integer_Text_IO;

with datuak;use datuak;
with kopiatu_dira;
procedure proba_kopiatu_dira is
 package ES_Booleanos is new Enumeration_IO(Boolean); use ES_Booleanos;
 Gel1:Gela;
 emaitza:Boolean;
begin
   Gel1(1,1).Okupatua:=true;
   Gel1(1,1).Azt.Hitz_kopuru_ezberdin:=4;
   Gel1(1,2).Okupatua:=true;
   Gel1(1,2).Azt.Hitz_kopuru_ezberdin:=4;
   Gel1(1,3).Okupatua:=false;
   Gel1(1,3).Azt.Hitz_kopuru_ezberdin:=0;
   Gel1(1,4).Okupatua:=true;
   Gel1(1,4).Azt.Hitz_kopuru_ezberdin:=7;   
   Gel1(1,5).Okupatua:=true;
   Gel1(1,5).Azt.Hitz_kopuru_ezberdin:=7;
   Gel1(1,6).Okupatua:=false;
   Gel1(1,6).Azt.Hitz_kopuru_ezberdin:=0;    
   Gel1(1,7).Okupatua:=false;
   Gel1(1,7).Azt.Hitz_kopuru_ezberdin:=0;    
   Gel1(1,8).Okupatua:=false;
   Gel1(1,8).Azt.Hitz_kopuru_ezberdin:=0;    
   Gel1(1,9).Okupatua:=false;
   Gel1(1,9).Azt.Hitz_kopuru_ezberdin:=0;    
   Gel1(1,10).Okupatua:=false;
   Gel1(1,10).Azt.Hitz_kopuru_ezberdin:=0; 
    
    Gel1(2,1).Okupatua:=true;
    Gel1(2,1).Azt.Hitz_kopuru_ezberdin:=4;
    Gel1(2,2).Okupatua:=true;
    Gel1(2,2).Azt.Hitz_kopuru_ezberdin:=4;
    Gel1(2,3).Okupatua:=false;
    Gel1(2,3).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(2,4).Okupatua:=true;
    Gel1(2,4).Azt.Hitz_kopuru_ezberdin:=7;   
    Gel1(2,5).Okupatua:=true;
    Gel1(2,5).Azt.Hitz_kopuru_ezberdin:=7;
    Gel1(2,6).Okupatua:=false;
    Gel1(2,6).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(2,7).Okupatua:=false;
    Gel1(2,7).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(2,8).Okupatua:=false;
    Gel1(2,8).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(2,9).Okupatua:=false;
    Gel1(2,9).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(2,10).Okupatua:=false;
    Gel1(2,10).Azt.Hitz_kopuru_ezberdin:=0;
    
    Gel1(3,1).Okupatua:=false;
    Gel1(3,1).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(3,2).Okupatua:=false;
    Gel1(3,2).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(3,3).Okupatua:=false;
    Gel1(3,3).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(3,4).Okupatua:=false;
    Gel1(3,4).Azt.Hitz_kopuru_ezberdin:=0;   
    Gel1(3,5).Okupatua:=false;
    Gel1(3,5).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(3,6).Okupatua:=false;
    Gel1(3,6).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(3,7).Okupatua:=false;
    Gel1(3,7).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(3,8).Okupatua:=false;
    Gel1(3,8).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(3,9).Okupatua:=false;
    Gel1(3,9).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(3,10).Okupatua:=false;
    Gel1(3,10).Azt.Hitz_kopuru_ezberdin:=0;     
    
    Gel1(4,1).Okupatua:=false;
    Gel1(4,1).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(4,2).Okupatua:=false;
    Gel1(4,2).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(4,3).Okupatua:=false;
    Gel1(4,3).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(4,4).Okupatua:=false;
    Gel1(4,4).Azt.Hitz_kopuru_ezberdin:=0;   
    Gel1(4,5).Okupatua:=false;
    Gel1(4,5).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(4,6).Okupatua:=false;
    Gel1(4,6).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(4,7).Okupatua:=false;
    Gel1(4,7).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(4,8).Okupatua:=false;
    Gel1(4,8).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(4,9).Okupatua:=false;
    Gel1(4,9).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(4,10).Okupatua:=false;
    Gel1(4,10).Azt.Hitz_kopuru_ezberdin:=0;      
    
    Gel1(5,1).Okupatua:=false;
    Gel1(5,1).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(5,2).Okupatua:=false;
    Gel1(5,2).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(5,3).Okupatua:=false;
    Gel1(5,3).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(5,4).Okupatua:=false;
    Gel1(5,4).Azt.Hitz_kopuru_ezberdin:=0;   
    Gel1(5,5).Okupatua:=false;
    Gel1(5,5).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(5,6).Okupatua:=false;
    Gel1(5,6).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(5,7).Okupatua:=false;
    Gel1(5,7).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(5,8).Okupatua:=false;
    Gel1(5,8).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(5,9).Okupatua:=false;
    Gel1(5,9).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(5,10).Okupatua:=false;
    Gel1(5,10).Azt.Hitz_kopuru_ezberdin:=0;     
    
    Gel1(6,1).Okupatua:=false;
    Gel1(6,1).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(6,2).Okupatua:=false;
    Gel1(6,2).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(6,3).Okupatua:=false;
    Gel1(6,3).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(6,4).Okupatua:=false;
    Gel1(6,4).Azt.Hitz_kopuru_ezberdin:=0;   
    Gel1(6,5).Okupatua:=false;
    Gel1(6,5).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(6,6).Okupatua:=false;
    Gel1(6,6).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(6,7).Okupatua:=false;
    Gel1(6,7).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(6,8).Okupatua:=false;
    Gel1(6,8).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(6,9).Okupatua:=false;
    Gel1(6,9).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(6,10).Okupatua:=false;
    Gel1(6,10).Azt.Hitz_kopuru_ezberdin:=0;     
    
    Gel1(7,1).Okupatua:=false;
    Gel1(7,1).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(7,2).Okupatua:=false;
    Gel1(7,2).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(7,3).Okupatua:=false;
    Gel1(7,3).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(7,4).Okupatua:=false;
    Gel1(7,4).Azt.Hitz_kopuru_ezberdin:=0;   
    Gel1(7,5).Okupatua:=false;
    Gel1(7,5).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(7,6).Okupatua:=false;
    Gel1(7,6).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(7,7).Okupatua:=false;
    Gel1(7,7).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(7,8).Okupatua:=false;
    Gel1(7,8).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(7,9).Okupatua:=false;
    Gel1(7,9).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(7,10).Okupatua:=false;
    Gel1(7,10).Azt.Hitz_kopuru_ezberdin:=0;     
    
    Gel1(8,1).Okupatua:=false;
    Gel1(8,1).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(8,2).Okupatua:=false;
    Gel1(8,2).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(8,3).Okupatua:=false;
    Gel1(8,3).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(8,4).Okupatua:=false;
    Gel1(8,4).Azt.Hitz_kopuru_ezberdin:=0;   
    Gel1(8,5).Okupatua:=false;
    Gel1(8,5).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(8,6).Okupatua:=false;
    Gel1(8,6).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(8,7).Okupatua:=false;
    Gel1(8,7).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(8,8).Okupatua:=false;
    Gel1(8,8).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(8,9).Okupatua:=false;
    Gel1(8,9).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(8,10).Okupatua:=false;
    Gel1(8,10).Azt.Hitz_kopuru_ezberdin:=0;     
    
    Gel1(9,1).Okupatua:=false;
    Gel1(9,1).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(9,2).Okupatua:=false;
    Gel1(9,2).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(9,3).Okupatua:=false;
    Gel1(9,3).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(9,4).Okupatua:=false;
    Gel1(9,4).Azt.Hitz_kopuru_ezberdin:=0;   
    Gel1(9,5).Okupatua:=false;
    Gel1(9,5).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(9,6).Okupatua:=false;
    Gel1(9,6).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(9,7).Okupatua:=false;
    Gel1(9,7).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(9,8).Okupatua:=false;
    Gel1(9,8).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(9,9).Okupatua:=false;
    Gel1(9,9).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(9,10).Okupatua:=false;
    Gel1(9,10).Azt.Hitz_kopuru_ezberdin:=0;     
          
    Gel1(10,1).Okupatua:=false;
    Gel1(10,1).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(10,2).Okupatua:=false;
    Gel1(10,2).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(10,3).Okupatua:=false;
    Gel1(10,3).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(10,4).Okupatua:=false;
    Gel1(10,4).Azt.Hitz_kopuru_ezberdin:=0;   
    Gel1(10,5).Okupatua:=false;
    Gel1(10,5).Azt.Hitz_kopuru_ezberdin:=0;
    Gel1(10,6).Okupatua:=false;
    Gel1(10,6).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(10,7).Okupatua:=false;
    Gel1(10,7).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(10,8).Okupatua:=false;
    Gel1(10,8).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(10,9).Okupatua:=false;
    Gel1(10,9).Azt.Hitz_kopuru_ezberdin:=0;    
    Gel1(10,10).Okupatua:=false;
    Gel1(10,10).Azt.Hitz_kopuru_ezberdin:=0;        
    
    New_line;
    skip_line;
    Put("Sakatu return jarraitzeko");
   for i in 1..Max_lerro loop
    for j in 1..Max_zutabe loop
        if Gel1(i,j).Okupatua=false or Gel1(i,j+1).Okupatua=false then
            Put(i,j);
            Put("   eta   ");
            Put(i,j+1);
            Put("Ez dira kopiatu");
            else
        Put(i,j);
        Put("   eta   ");
        Put(i,j+1);
        Put("kopiatu dira:");
emaitza:=kopiatu_dira(Gel1(i,j).Azt,Gel1(i,j+1).Azt);
        Put(emaitza);
        end if;
        New_line;
        if Gel1(i,j).Okupatua=false or Gel1(i,j+1).Okupatua=false then
            Put(i,j);
            Put("   eta   ");
            Put(i+1,j);
            Put("Ez dira kopiatu");
        else
            put(i,j);
            Put("   eta   ");
            put(i+1,j);
            Put("kopiatu dira:");
        emaitza:=kopiatu_dira(Gel1(i,j).Azt,Gel1(i+1,j).Azt);
        Put(emaitza);
        end if;
            New_line;
    end loop;
end loop; 
        New_line(3);
        Put("emaitzak hauek izan beharko lirateke:");
        New_line;
        Put("1-1 eta 1-2 kopiatu egin dita");
        Put("1-4eta 1-5kopiatu egin dira");
        Put("1-1eta 2-1kopiatu egin dira");
        Put("1-2eta 2-2kopiatu egin dira");
        Put("2-1eta 2-2kopiatu egin dira");
end proba_kopiatu_dira;